### ISSUE TITLE
Compatibility with Python 3.7

### ISSUE THREAD

**Issue by stormvirux** [djordon/queueing-tool#55]
The package does not seem to install with python 3.7. 

`pip3 install queueing-tool`

returns

```
Installing collected packages: queueing-tool
  Running setup.py install for queueing-tool ... error
    Complete output from command /Users/mohammt1/.virtualenvs/totem/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/88/h0b7gdt53sdf4_13d8q4q3n8012sxd/T/pip-install-u316q5r0/queueing-tool/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/88/h0b7gdt53sdf4_13d8q4q3n8012sxd/T/pip-record-5q8_088q/install-record.txt --single-version-externally-managed --compile --install-headers /Users/mohammt1/.virtualenvs/totem/bin/../include/site/python3.7/queueing-tool:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.13-x86_64-3.7
    creating build/lib.macosx-10.13-x86_64-3.7/queueing_tool
    copying queueing_tool/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/queueing_tool
    copying queueing_tool/union_find.py -> build/lib.macosx-10.13-x86_64-3.7/queueing_tool
    creating build/lib.macosx-10.13-x86_64-3.7/queueing_tool/graph
    copying queueing_tool/graph/graph_generation.py -> build/lib.macosx-10.13-x86_64-3.7/queueing_tool/graph
    copying queueing_tool/graph/graph_wrapper.py -> build/lib.macosx-10.13-x86_64-3.7/queueing_tool/graph
    copying queueing_tool/graph/graph_functions.py -> build/lib.macosx-10.13-x86_64-3.7/queueing_tool/graph
    copying queueing_tool/graph/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/queueing_tool/graph
    copying queueing_tool/graph/graph_preparation.py -> build/lib.macosx-10.13-x86_64-3.7/queueing_tool/graph
    creating build/lib.macosx-10.13-x86_64-3.7/queueing_tool/network
    copying queueing_tool/network/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/queueing_tool/network
    copying queueing_tool/network/queue_network.py -> build/lib.macosx-10.13-x86_64-3.7/queueing_tool/network
    creating build/lib.macosx-10.13-x86_64-3.7/queueing_tool/queues
    copying queueing_tool/queues/queue_servers.py -> build/lib.macosx-10.13-x86_64-3.7/queueing_tool/queues
    copying queueing_tool/queues/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/queueing_tool/queues
    copying queueing_tool/queues/agents.py -> build/lib.macosx-10.13-x86_64-3.7/queueing_tool/queues
    copying queueing_tool/queues/queue_extentions.py -> build/lib.macosx-10.13-x86_64-3.7/queueing_tool/queues
    running build_ext
    building 'queueing_tool.network.priority_queue' extension
    creating build/temp.macosx-10.13-x86_64-3.7
    creating build/temp.macosx-10.13-x86_64-3.7/queueing_tool
    creating build/temp.macosx-10.13-x86_64-3.7/queueing_tool/network
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/Users/mohammt1/Homebrew/opt/ncurses/include -I/Users/mohammt1/Homebrew/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c queueing_tool/network/priority_queue.c -o build/temp.macosx-10.13-x86_64-3.7/queueing_tool/network/priority_queue.o
    queueing_tool/network/priority_queue.c:19405:21: error: no member named 'exc_type' in 'struct _ts'
        *type = tstate->exc_type;
                ~~~~~~  ^
    queueing_tool/network/priority_queue.c:19406:22: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
        *value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
    /Users/mohammt1/Homebrew/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    queueing_tool/network/priority_queue.c:19407:19: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
        *tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
    /Users/mohammt1/Homebrew/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    queueing_tool/network/priority_queue.c:19414:24: error: no member named 'exc_type' in 'struct _ts'
        tmp_type = tstate->exc_type;
                   ~~~~~~  ^
    queueing_tool/network/priority_queue.c:19415:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
        tmp_value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
    /Users/mohammt1/Homebrew/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    queueing_tool/network/priority_queue.c:19416:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
        tmp_tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
    /Users/mohammt1/Homebrew/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    queueing_tool/network/priority_queue.c:19417:13: error: no member named 'exc_type' in 'struct _ts'
        tstate->exc_type = type;
        ~~~~~~  ^
    queueing_tool/network/priority_queue.c:19418:13: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
        tstate->exc_value = value;
                ^~~~~~~~~
                curexc_value
    /Users/mohammt1/Homebrew/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    queueing_tool/network/priority_queue.c:19419:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
        tstate->exc_traceback = tb;
                ^~~~~~~~~~~~~
                curexc_traceback
    /Users/mohammt1/Homebrew/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    queueing_tool/network/priority_queue.c:19474:24: error: no member named 'exc_type' in 'struct _ts'
        tmp_type = tstate->exc_type;
                   ~~~~~~  ^
    queueing_tool/network/priority_queue.c:19475:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
        tmp_value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
    /Users/mohammt1/Homebrew/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    queueing_tool/network/priority_queue.c:19476:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
        tmp_tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
    /Users/mohammt1/Homebrew/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    queueing_tool/network/priority_queue.c:19477:13: error: no member named 'exc_type' in 'struct _ts'
        tstate->exc_type = local_type;
        ~~~~~~  ^
    queueing_tool/network/priority_queue.c:19478:13: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
        tstate->exc_value = local_value;
                ^~~~~~~~~
                curexc_value
    /Users/mohammt1/Homebrew/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    queueing_tool/network/priority_queue.c:19479:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
        tstate->exc_traceback = local_tb;
                ^~~~~~~~~~~~~
                curexc_traceback
    /Users/mohammt1/Homebrew/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    queueing_tool/network/priority_queue.c:19501:24: error: no member named 'exc_type' in 'struct _ts'
        tmp_type = tstate->exc_type;
                   ~~~~~~  ^
    queueing_tool/network/priority_queue.c:19502:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
        tmp_value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
    /Users/mohammt1/Homebrew/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    queueing_tool/network/priority_queue.c:19503:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
        tmp_tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
    /Users/mohammt1/Homebrew/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    queueing_tool/network/priority_queue.c:19504:13: error: no member named 'exc_type' in 'struct _ts'
        tstate->exc_type = *type;
        ~~~~~~  ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command 'clang' failed with exit status 1

    ----------------------------------------
Command "/Users/mohammt1/.virtualenvs/totem/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/88/h0b7gdt53sdf4_13d8q4q3n8012sxd/T/pip-install-u316q5r0/queueing-tool/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/88/h0b7gdt53sdf4_13d8q4q3n8012sxd/T/pip-record-5q8_088q/install-record.txt --single-version-externally-managed --compile --install-headers /Users/mohammt1/.virtualenvs/totem/bin/../include/site/python3.7/queueing-tool" failed with error code 1 in /private/var/folders/88/h0b7gdt53sdf4_13d8q4q3n8012sxd/T/pip-install-u316q5r0/queueing-tool/

```

I tried the same on Travis-CI with python 3.7 and got 

```
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -coverage -fPIC -I/opt/python/3.7.1/include/python3.7m -c queueing_tool/network/priority_queue.c -o build/temp.linux-x86_64-3.7/queueing_tool/network/priority_queue.o
    queueing_tool/network/priority_queue.c: In function ‘__Pyx__ExceptionSave’:
    queueing_tool/network/priority_queue.c:19405:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         *type = tstate->exc_type;
                       ^
    queueing_tool/network/priority_queue.c:19406:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         *value = tstate->exc_value;
                        ^
    queueing_tool/network/priority_queue.c:19407:17: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         *tb = tstate->exc_traceback;
                     ^
    queueing_tool/network/priority_queue.c: In function ‘__Pyx__ExceptionReset’:
    queueing_tool/network/priority_queue.c:19414:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    queueing_tool/network/priority_queue.c:19415:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    queueing_tool/network/priority_queue.c:19416:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    queueing_tool/network/priority_queue.c:19417:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tstate->exc_type = type;
               ^
    queueing_tool/network/priority_queue.c:19418:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tstate->exc_value = value;
               ^
    queueing_tool/network/priority_queue.c:19419:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tstate->exc_traceback = tb;
               ^
    queueing_tool/network/priority_queue.c: In function ‘__Pyx__GetException’:
    queueing_tool/network/priority_queue.c:19474:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    queueing_tool/network/priority_queue.c:19475:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    queueing_tool/network/priority_queue.c:19476:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    queueing_tool/network/priority_queue.c:19477:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tstate->exc_type = local_type;
               ^
    queueing_tool/network/priority_queue.c:19478:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tstate->exc_value = local_value;
               ^
    queueing_tool/network/priority_queue.c:19479:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tstate->exc_traceback = local_tb;
               ^
    queueing_tool/network/priority_queue.c: In function ‘__Pyx__ExceptionSwap’:
    queueing_tool/network/priority_queue.c:19501:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    queueing_tool/network/priority_queue.c:19502:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    queueing_tool/network/priority_queue.c:19503:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    queueing_tool/network/priority_queue.c:19504:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tstate->exc_type = *type;
               ^
    queueing_tool/network/priority_queue.c:19505:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tstate->exc_value = *value;
               ^
    queueing_tool/network/priority_queue.c:19506:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tstate->exc_traceback = *tb;
               ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------

The command "pip install -e ." failed and exited with 1 during .
```

Is there any work around to make it work with 3.7?

**Comment by djordon** [comment]
Oh man, sorry for the delay in getting back to you @stormvirux. Yes there is. Hopefully I'll have some time to get to it this weekend. Stay tuned

**Comment by djordon** [comment]
@stormvirux I've uploaded a new version of queueing-tool (`v1.2.3`) that works with python 3.7. Let me know if you encounter any issues.
